# Generated by Django 4.0.5 on 2022-06-10 00:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0002_rename_created_at_despesa_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.tipodespesa'),
        ),
    ]
