# Generated by Django 4.0.5 on 2022-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0006_remove_despesa_user_remove_tipodespesa_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
