# Generated by Django 4.0.5 on 2022-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0010_alter_tipodespesa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
