# Generated by Django 4.0.5 on 2022-06-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0011_tipodespesa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodespesa',
            name='descricao',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='valor_normal',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=18, null=True),
        ),
    ]
