# Generated by Django 4.0.5 on 2022-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0012_alter_tipodespesa_descricao_alter_tipodespesa_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodespesa',
            name='valor_normal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
