# Generated by Django 4.0.5 on 2022-06-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0018_alter_tipodespesa_valor_normal'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='user',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.tipodespesa'),
        ),
    ]
