# Generated by Django 4.0.5 on 2022-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0020_alter_despesa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
