# Generated by Django 4.0.5 on 2022-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0021_alter_despesa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodespesa',
            name='descricao',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='valor_normal',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
