# Generated by Django 4.0.5 on 2022-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0022_alter_tipodespesa_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='descricao',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
