# Generated by Django 4.0.5 on 2022-06-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0023_alter_despesa_descricao_alter_despesa_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodespesa',
            name='valor_normal',
        ),
    ]
