# Generated by Django 4.0.5 on 2022-06-14 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0024_remove_tipodespesa_valor_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 25, 30, 701200), null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 25, 30, 701200), null=True),
        ),
    ]
