# Generated by Django 4.0.5 on 2022-06-14 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0025_alter_despesa_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 53, 33, 850836), null=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 53, 33, 849834), null=True),
        ),
    ]
