# Generated by Django 4.0.5 on 2022-06-14 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0026_alter_despesa_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='despesa',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 56, 17, 49469), null=True),
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 0, 56, 17, 48469), null=True),
        ),
    ]
